<?php

/**
 * @file
 * Install function for the Triplestore Indexer Test module.
 */

/**
 * Implements hook_install().
 */
function triplestore_indexer_test_install() {
  \Drupal::configFactory()->getEditable('rest.resource.entity.file')->delete();
  \Drupal::configFactory()->getEditable('rest.resource.entity.media')->delete();
  \Drupal::configFactory()->getEditable('rest.resource.entity.node')->delete();
  \Drupal::configFactory()->getEditable('rest.resource.entity.taxonomy_term')->delete();
}
