name: CI

on:
  push:
    branches: [ 2.x ]
  pull_request:
    branches: [ 2.x ]
  workflow_dispatch:

jobs:
  islandora-module-ci:
    uses: digitalutsc/reusable_workflows/.github/workflows/islandora-module-ci.yml@main
    with:
      module_name: triplestore_indexer
      install_chromedriver: true
