# This is a basic workflow to help you get started with Actions
# Based on https://github.com/Islandora/islandora/blob/c1aa0a5f2f593440b607b73245e103a9b6626371/.github/workflows/build-2.x.yml

name: CI

# Controls when the action will run.
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allowed_failure }}
    strategy:
      fail-fast: false
      matrix:
        php-versions: ["7.3", "7.4"]
        test-suite: ["functional"]
        drupal-version: ["9.3.x", "9.4.x-dev"]
        allowed_failure: [false]
        mysql: ["5.7"]

    name: PHP ${{ matrix.php-versions }} | drupal ${{ matrix.drupal-version }} | mysql ${{ matrix.mysql }} | test-suite ${{ matrix.test-suite }}

    services:
      mysql:
        image: mysql:${{ matrix.mysql }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: drupal
        ports:
          - 3306:3306
      activemq:
        image: webcenter/activemq:5.14.3
        ports:
          - 8161:8161
          - 61616:61616
          - 61613:61613

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: build_dir

      - name: Checkout islandora_ci
        uses: actions/checkout@v2
        with:
          repository: islandora/islandora_ci
          ref: github-actions
          path: islandora_ci

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Setup Mysql client
        run: |
          sudo apt-get update
          sudo apt-get remove -y mysql-client mysql-common
          sudo apt-get install -y mysql-client

      - name: Set environment variables
        run: |
          echo "DRUPAL_VERSION=${{ matrix.drupal-version }}" >> $GITHUB_ENV
          echo "SCRIPT_DIR=$GITHUB_WORKSPACE/islandora_ci" >> $GITHUB_ENV
          echo "DRUPAL_DIR=/opt/drupal" >> $GITHUB_ENV
          echo "PHPUNIT_FILE=$GITHUB_WORKSPACE/build_dir/phpunit.xml" >> $GITHUB_ENV

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Setup Drupal
        run: |
          mkdir $DRUPAL_DIR
          $SCRIPT_DIR/travis_setup_drupal.sh
          cd $DRUPAL_DIR
          chmod -R u+w web/sites/default
          mkdir -p web/sites/simpletest/browser_output

      - name: Setup composer paths
        run: |
          git -C "$GITHUB_WORKSPACE/build_dir" checkout -b github-testing
          cd $DRUPAL_DIR
          composer config repositories.local path "$GITHUB_WORKSPACE/build_dir"
          composer config minimum-stability dev
          composer require "digitalutsc/triplestore_indexer"

      - name: Install modules
        run: |
          cd $DRUPAL_DIR/web
          drush --uri=127.0.0.1:8282 en -y triplestore_indexer

      - name: Copy PHPunit file
        run: cp $PHPUNIT_FILE $DRUPAL_DIR/web/core/phpunit.xml

      - name: Test scripts
        run: $SCRIPT_DIR/travis_scripts.sh
        
      - name: Install drupal-check
        run: composer global require mglaman/drupal-check

      - name: Run drupal-check
        continue-on-error: true
        run: |
          drupal-check --drupal-root $DRUPAL_DIR $DRUPAL_DIR/web/modules/contrib/triplestore_indexer
      
      - name: PHPUNIT tests
        run: |
          cd $DRUPAL_DIR/web/core
          $DRUPAL_DIR/vendor/bin/phpunit --verbose --testsuite "${{ matrix.test-suite }}"
